services:
  api-solid-pg:
    image: bitnami/postgresql
    container_name: find-a-friend-pg
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=findafriend
    ports:
      - '5432:5432'